### ISSUE TITLE
Shop.html

### ISSUE THREAD

**Issue by Nic0Joos** [Nic0Joos/Unchained#4]
Nothin can be clicked on the page (frozen)

When trying with postman for api/order, the server responds with status code 415

**Comment by Nic0Joos** [comment]
Uncaught reference errors (Line 149 and 157 in shop.html / Line 68 in app.js)

**Comment by Nic0Joos** [comment]
Nothing can be clicked

**Comment by LennartCaroli** [comment]
no error message, but entire shop page is frozen and not clickable even though everything is loaded

after inputting amount of  products and "calculate costs" is clicked, API/costrequest should send final calculation to the backend

**Comment by Nic0Joos** [comment]
Resolved
